import type { Prisma } from "../db/prisma";
import { EngineeringAgent } from "../agents/engineeringAgent";
import { buildEngineeringAgentSystemPrompt } from "../agents/engineeringAgentPrompt";
import { normalizeImplementationOutput } from "../agents/normalizeImplementationOutput";
import { runCanaryCycle } from "../canaryAgent";
import { runEngineeringCodingAgentic } from "../engineeringCodingAgent";
import { resolveCodingBranchName } from "../engineeringCodingAgent/inputBuilder";
import { gatherTechPrewriteContext } from "../engineeringCodingAgent/prewriteContext";
import {
  assertQaHandoffReady,
  buildReadyQaHandoff,
  type QaHandoff,
} from "../engineering/qaHandoff";
import { buildPipelineRunSummary } from "./runSummary";
import {
  clearCodingArtifacts,
  getCodingArtifacts,
  setCodingDeliverablePaths,
  snapshotCodingArtifacts,
} from "../engineering/codingArtifactStore";
import {
  resolveDeliverableFiles,
  resolveImplementationMode,
  resolveTargetFilePaths,
} from "../engineering/resolveImplementationMode";
import { emitEngineeringCodingEvent } from "../engineering/codingEventsHub";
import {
  findMissingContentDeliverables,
  reconcileContentDeliverables,
  resolveContentDeliverablePaths,
} from "../engineering/contentDeliverables";
import {
  createEngWorkspace,
  destroyEngWorkspace,
  getEngWorkspace,
  resolveFallbackApiPushBranch,
  sanitizeGitShellError,
  shouldSkipEngineeringDependencyInstall,
  workspaceCommitAndPush,
  workspaceCommittedDiff,
  workspaceGetChangedFiles,
  workspaceGitDiff,
} from "../engineering/engineeringWorkspace";
import { normalizeRepoPath } from "../integrations/git/normalizePushFiles";
import { runWorkspaceSafetyCompile } from "../engineering/workspaceCompile";
import { publishPipelineArtifact, mirrorPmContextArtifacts } from "./artifacts";
import { resolveRepoIndexBranch } from "../git-integration/resolveRepoBranch";
import { normalizePushFiles } from "../integrations/git/normalizePushFiles";
import { gitClient } from "../integrations/gitProvider";
import { getKnowledge } from "../codebaseIntelligence/knowledgeService";
import { runQaAgentic } from "../qaAgent";
import { resolveImplementationBranchForQa } from "../qa/resolveImplementationBranch";
import {
  assertPipelineNotCancelled,
  clearPipelineCancel,
  PipelineCancelledError,
} from "./cancelSession";
import { completeTicketInJira } from "../jira/writeback/completeTicketInJira";
import {
  persistBranchState,
  writeEngineeringToTicket,
  writeGitPushToTicket,
  writePrdToTicket,
  writeQaToTicket,
} from "../jira/writeback/stageWriteback";
import type { QaExecutionReport } from "../qa/report/reportGenerator";
import type { GeneratedPRD } from "../prd/prdGenerator";
import { orgIntelligence } from "../orgIntelligence";
import { buildEnrichedCodebaseContext } from "../codebaseIntelligence/enrichedContextService";
import { resolveRepoScope } from "../codebaseIntelligence/repoScope";
import {
  DiscoveryPausedError,
  runDiscovery,
} from "../discovery/discoveryOrchestrator";
import type { DiscoveryPauseSnapshot } from "../discovery/persistedContext";
import { answersCoverAllQuestions } from "../discovery/persistedContext";
import { auditRepo } from "../db/repositories/auditRepo";
import { pipelineRepo } from "../db/repositories/pipelineRepo";
import { ticketRepo } from "../db/repositories/ticketRepo";
import { indexer } from "../rag/indexer";
import { retriever } from "../rag/retriever";
import { unifiedRetriever } from "../rag/unifiedRetriever";
import type {
  AgentOutput,
  ImplementationOutput,
  PrdOutput,
  QaOutput,
} from "../types/agents";
import type { NormalizedTicket } from "../types/ticket";
import type { GateResult, ValidationResult } from "../types/pipeline";
import { logger } from "../utils/logger";
import { applyGateDecision, asGateResult, extractOriginalTicket, runGate, stampOriginalTicket } from "../gates";
import { buildEngineeringAgentContext } from "./contextBuilder";
import { stateManager } from "./stateManager";

/** Build a draft PR body from the implementation context */
function buildPrBody(jiraKey: string, prd: PrdOutput, codingSummary: string): string {
  const criteria = prd.acceptanceCriteria
    .slice(0, 8)
    .map((c, i) => `- [ ] ${i + 1}. ${c}`)
    .join("\n");
  return [
    `## ${prd.title}`,
    "",
    `**Jira:** ${jiraKey}`,
    "",
    "### Summary",
    codingSummary || prd.proposedSolution,
    "",
    "### Acceptance criteria",
    criteria,
    "",
    "_Generated by AgentOX engineering agent — review and approve before merging._",
  ].join("\n");
}

function buildPrBodyWithQa(
  jiraKey: string,
  prd: PrdOutput,
  codingSummary: string,
  qa: import("../types/agents").QaOutput,
  executionReport?: Record<string, unknown>
): string {
  const criteria = prd.acceptanceCriteria
    .slice(0, 8)
    .map((c, i) => {
      const covered = qa.testCases.some((tc) => tc.linkedCriterion?.includes(c.slice(0, 30)));
      return `- [${covered ? "x" : " "}] ${i + 1}. ${c}`;
    })
    .join("\n");

  const testRun = (executionReport as { testRun?: { passed?: number; failed?: number; totalTests?: number } } | undefined)?.testRun;
  const recommendation = (executionReport as { overallRecommendation?: string } | undefined)?.overallRecommendation;

  const qaSection = [
    "### QA results",
    `**Tests:** ${qa.testCases.length} · **Coverage:** ${qa.coverageReport.coveragePercent.toFixed(1)}% · **Confidence:** ${(qa.confidenceScore * 100).toFixed(0)}%`,
    testRun
      ? `**Test run:** ${testRun.passed ?? 0} passed · ${testRun.failed ?? 0} failed · ${testRun.totalTests ?? 0} total`
      : null,
    recommendation
      ? `**Recommendation:** ${recommendation.replace(/_/g, " ")}`
      : null,
    qa.riskAreas.length > 0
      ? `**Risk areas:** ${qa.riskAreas.slice(0, 3).join(", ")}`
      : null,
  ]
    .filter(Boolean)
    .join("\n");

  return [
    `## ${prd.title}`,
    "",
    `**Jira:** ${jiraKey}`,
    "",
    "### Summary",
    codingSummary || prd.proposedSolution,
    "",
    "### Acceptance criteria",
    criteria,
    "",
    qaSection,
    "",
    "_Generated by AgentOX · QA validated — ready for human review._",
  ].join("\n");
}

const CANARY_PIPELINE_TIMEOUT_MS = 8 * 60 * 1000; // 8 minutes — canary must not stall the whole pipeline

async function runCanaryWithTimeout(
  input: Parameters<typeof runCanaryCycle>[0]
): Promise<Awaited<ReturnType<typeof runCanaryCycle>>> {
  const timeoutPromise = new Promise<null>((resolve) =>
    setTimeout(() => resolve(null), CANARY_PIPELINE_TIMEOUT_MS)
  );
  const result = await Promise.race([runCanaryCycle(input), timeoutPromise]);
  if (result === null) {
    logger.warn(
      { pipelineId: input.pipelineId, jiraKey: input.jiraKey },
      "canary cycle timed out after 8 minutes — skipping security gate canary check"
    );
  }
  return result;
}

async function updatePrAfterQa(
  jiraKey: string,
  qa: import("../types/agents").QaOutput,
  prd: PrdOutput,
  codingSummary: string,
  executionReport?: Record<string, unknown>
): Promise<void> {
  try {
    const { prisma } = await import("../db/client");
    const row = await prisma.branchState.findFirst({
      where: { jiraKey },
      orderBy: { updatedAt: "desc" },
    });
    if (!row?.prNumber) return;
    const newBody = buildPrBodyWithQa(jiraKey, prd, codingSummary, qa, executionReport);
    await gitClient.updatePullRequest(row.prNumber, { body: newBody });
    // Mark PR as ready for review (not draft) if QA passes
    await gitClient.updatePullRequest(row.prNumber, { draft: false });
    await prisma.branchState.updateMany({
      where: { jiraKey, prNumber: row.prNumber },
      data: { prStatus: "open" },
    });
  } catch (err) {
    logger.warn({ err, jiraKey }, "updatePrAfterQa failed — non-fatal");
  }
}

export class PipelineOrchestrator {
  private readonly engineeringAgent = new EngineeringAgent();

  async run(ticketId: string): Promise<void> {
    const ticket = await ticketRepo.findById(ticketId);
    if (!ticket) throw new Error(`Ticket ${ticketId} not found`);

    const normalizedTicket = ticket.normalizedData as unknown as NormalizedTicket;
    const pipeline = await pipelineRepo.create({
      ticketId: ticket.id,
      currentStage: "INGESTION",
      status: "RUNNING",
    });

    clearPipelineCancel(pipeline.id, ticket.jiraKey);

    logger.info({ pipelineId: pipeline.id, ticketId }, "pipeline started");
    await ticketRepo.setStatus(ticket.id, "PROCESSING");
    await auditRepo.log(pipeline.id, "PIPELINE_STARTED", {
      ticketId: ticket.id,
      jiraKey: ticket.jiraKey,
    });

    try {
      await this.ingest(pipeline.id, normalizedTicket);

      const productStage = await this.runProductAgent(
        pipeline.id,
        normalizedTicket.jiraKey,
        normalizedTicket,
      );
      const prdValidation = await this.validatePrdStage(
        pipeline.id,
        productStage.agentOutput,
        normalizedTicket,
        productStage.enrichedPrdDocument
      );
      await orgIntelligence.captureValidation({
        pipelineId: pipeline.id,
        jiraKey: normalizedTicket.jiraKey,
        sourceType: "PRD",
        validation: prdValidation,
        components: normalizedTicket.components ?? [],
      });
      if (!(await applyGateDecision(pipeline.id, "prd", prdValidation))) {
        await ticketRepo.setStatus(ticket.id, "AWAITING_HUMAN");
        return;
      }
      await writePrdToTicket(
        normalizedTicket.jiraKey,
        productStage.agentOutput.parsed,
        this.extractGeneratedPrd(productStage.enrichedPrdDocument, productStage.agentOutput)
      );
      await indexer.indexPrd(
        normalizedTicket.jiraTicketId,
        normalizedTicket.jiraKey,
        productStage.agentOutput.parsed
      );

      this.assertNotStopped(pipeline.id, normalizedTicket.jiraKey);

      const engStage = await this.runEngineeringAgent(
        pipeline.id,
        normalizedTicket,
        productStage.agentOutput.parsed,
        productStage.enrichedPrdDocument
      );
      let codingStage: Awaited<ReturnType<typeof this.runEngineeringCodingAgent>>;
      try {
        codingStage = await this.runEngineeringCodingAgent(
          pipeline.id,
          normalizedTicket,
          productStage.agentOutput.parsed,
          engStage.output,
          productStage.enrichedPrdDocument,
          engStage.stageLogId
        );
      } catch (err) {
        // Close the ENGINEERING_AGENT stage log so it doesn't stay RUNNING
        // forever and confuse resume()'s completed-stage detection.
        await pipelineRepo
          .failStage(engStage.stageLogId, err instanceof Error ? err.message : String(err))
          .catch(() => undefined);
        throw err;
      }
      const implementationBranch = codingStage.implementationBranch;
      const qaHandoff = codingStage.qaHandoff;
      const implementationOutput = codingStage.output;
      const implementationValidation = await this.validateImplementationStage(
        pipeline.id,
        implementationOutput,
        productStage.agentOutput.parsed,
        normalizedTicket,
        productStage.enrichedPrdDocument
      );
      await orgIntelligence.captureValidation({
        pipelineId: pipeline.id,
        jiraKey: normalizedTicket.jiraKey,
        sourceType: "ENGINEERING",
        validation: implementationValidation,
        components: normalizedTicket.components ?? [],
        implementation: implementationOutput.parsed,
      });
      if (
        !(await applyGateDecision(
          pipeline.id,
          "implementation",
          implementationValidation
        ))
      ) {
        await ticketRepo.setStatus(ticket.id, "AWAITING_HUMAN");
        return;
      }
      await indexer.indexImplementation(
        normalizedTicket.jiraTicketId,
        normalizedTicket.jiraKey,
        implementationOutput.parsed
      );

      this.assertNotStopped(pipeline.id, normalizedTicket.jiraKey);

      const qaStage = await this.runQaAgent(
        pipeline.id,
        normalizedTicket.jiraKey,
        productStage.agentOutput.parsed,
        implementationOutput.parsed,
        implementationBranch,
        qaHandoff
      );
      const qaOutput = qaStage.agentOutput;

      const canaryChangedFiles = (implementationOutput.parsed.codeChanges ?? [])
        .map((c) => c.filePath)
        .filter(Boolean);
      const canaryResult = await runCanaryWithTimeout({
        pipelineId: pipeline.id,
        jiraKey: normalizedTicket.jiraKey,
        trigger: "pipeline",
        environment: "staging",
        scope: canaryChangedFiles.length > 0 ? "changed_files" : "full",
        orientation: {
          prdSummary: productStage.agentOutput.parsed.title,
          implementationSummary: implementationOutput.parsed.summary,
          qaSummary: qaOutput.parsed.testSummary,
          changedFiles: canaryChangedFiles,
        },
      });

      const qaValidation = await this.validateQaStage(
        pipeline.id,
        qaOutput,
        productStage.agentOutput.parsed,
        qaStage,
        normalizedTicket,
        canaryResult
      );
      await orgIntelligence.captureValidation({
        pipelineId: pipeline.id,
        jiraKey: normalizedTicket.jiraKey,
        sourceType: "QA_FAILURE",
        validation: qaValidation,
        components: normalizedTicket.components ?? [],
        qa: qaOutput.parsed,
      });
      if (!(await applyGateDecision(pipeline.id, "qa", qaValidation))) {
        await ticketRepo.setStatus(ticket.id, "AWAITING_HUMAN");
        return;
      }
      // Write QA results to Jira only after the QA gate passes — otherwise the
      // ticket would show QA as done while the pipeline is paused for review.
      await writeQaToTicket(
        normalizedTicket.jiraKey,
        qaOutput.parsed,
        qaStage.executionReport
      );
      if (canaryResult?.findings.length) {
        await auditRepo.log(pipeline.id, "CANARY_FINDINGS", {
          runId: canaryResult.runId,
          count: canaryResult.findings.length,
          critical: canaryResult.findings.filter((f) => f.severity === "critical").length,
        });
      }

      // Update PR body with QA results + mark ready for review
      await updatePrAfterQa(
        normalizedTicket.jiraKey,
        qaOutput.parsed,
        productStage.agentOutput.parsed,
        implementationOutput.parsed.codingSummary ?? implementationOutput.parsed.summary,
        qaStage.executionReport as Record<string, unknown> | undefined
      );

      await indexer.indexQaReport(
        normalizedTicket.jiraTicketId,
        normalizedTicket.jiraKey,
        qaOutput.parsed
      );

      const generatedPrd = this.extractGeneratedPrd(productStage.enrichedPrdDocument, productStage.agentOutput);
      const canaryCriticals = canaryResult?.findings
        .filter((f) => f.severity === "critical")
        .map((f) => ({ title: f.title, description: f.description })) ?? [];

      const jiraResult = await this.completeOutputStage(pipeline.id, normalizedTicket.jiraKey, {
        prd: productStage.agentOutput.parsed,
        generatedPrd,
        implementation: implementationOutput.parsed,
        qa: qaOutput.parsed,
        executionReport: qaStage.executionReport as Record<string, unknown> | undefined,
        validations: {
          prd: prdValidation,
          implementation: implementationValidation,
          qa: qaValidation,
        },
        canaryCriticals,
      });

      await orgIntelligence.capturePipelineComplete({
        pipelineId: pipeline.id,
        jiraKey: normalizedTicket.jiraKey,
        components: normalizedTicket.components ?? [],
        prd: productStage.agentOutput.parsed,
        implementation: implementationOutput.parsed,
        qa: qaOutput.parsed,
        validations: { prd: prdValidation, implementation: implementationValidation, qa: qaValidation },
      });

      await auditRepo.log(pipeline.id, "JIRA_WRITEBACK_COMPLETED", {
        jiraKey: normalizedTicket.jiraKey,
        ...jiraResult,
      });

      await this.publishCompletedRunSummary({
        pipelineId: pipeline.id,
        jiraKey: normalizedTicket.jiraKey,
        prd: productStage.agentOutput.parsed,
        implementation: implementationOutput.parsed,
        qa: qaOutput.parsed,
        implementationBranch,
        executionReport: qaStage.executionReport as Record<string, unknown> | undefined,
      });
      await stateManager.complete(pipeline.id);
      await ticketRepo.setStatus(ticket.id, "COMPLETED");
      logger.info({ pipelineId: pipeline.id, jiraResult }, "pipeline completed");
    } catch (err) {
      if (err instanceof DiscoveryPausedError) {
        await ticketRepo.setStatus(ticket.id, "AWAITING_HUMAN");
        logger.warn(
          { pipelineId: pipeline.id, blockingGaps: err.blockingGaps },
          "discovery paused for human clarification"
        );
        return;
      }
      if (err instanceof PipelineCancelledError) {
        logger.info({ pipelineId: pipeline.id }, "pipeline stopped by user");
        return;
      }
      const message = err instanceof Error ? err.message : String(err);
      const failedPipeline = await pipelineRepo.findById(pipeline.id);
      await stateManager.fail(
        pipeline.id,
        failedPipeline?.currentStage ?? pipeline.currentStage,
        message
      );
      await ticketRepo.setStatus(ticket.id, "FAILED");
      logger.error({ err, pipelineId: pipeline.id }, "pipeline failed");
      throw err;
    }
  }

  async resume(pipelineId: string): Promise<void> {
    const pipeline = await pipelineRepo.findById(pipelineId);
    if (!pipeline) throw new Error(`Pipeline ${pipelineId} not found`);

    const ticket = pipeline.ticket;
    const normalizedTicket = ticket.normalizedData as unknown as NormalizedTicket;
    const completedStages = new Set(await pipelineRepo.listCompletedStages(pipelineId));

    logger.info({ pipelineId, completedStages: [...completedStages] }, "pipeline resume started");
    clearPipelineCancel(pipelineId, ticket.jiraKey);
    await pipelineRepo.setStage(pipelineId, pipeline.currentStage, "RUNNING");
    await ticketRepo.setStatus(ticket.id, "PROCESSING");
    await auditRepo.log(pipelineId, "PIPELINE_RESUMED", { ticketId: ticket.id });

    try {
      if (!completedStages.has("INGESTION")) {
        await this.ingest(pipelineId, normalizedTicket);
      }

      let productStage: {
        agentOutput: AgentOutput<PrdOutput>;
        enrichedPrdDocument: Record<string, unknown>;
      };
      if (!completedStages.has("PRODUCT_AGENT")) {
        productStage = await this.runProductAgent(pipelineId, normalizedTicket.jiraKey, normalizedTicket);
      } else {
        productStage = this.loadProductStageFromLog(
          (await pipelineRepo.getStageOutput(pipelineId, "PRODUCT_AGENT"))!
        );
      }

      let prdValidation: GateResult;
      const prdValLog = await pipelineRepo.getStageOutput(pipelineId, "PRD_VALIDATION");
      if (prdValLog?.validationResult) {
        prdValidation = asGateResult(
          "prd",
          prdValLog.validationResult as unknown as ValidationResult
        );
      } else {
        prdValidation = await this.validatePrdStage(
          pipelineId,
          productStage.agentOutput,
          normalizedTicket,
          productStage.enrichedPrdDocument
        );
      }
      if (!(await applyGateDecision(pipelineId, "prd", prdValidation))) {
        await ticketRepo.setStatus(ticket.id, "AWAITING_HUMAN");
        return;
      }
      await writePrdToTicket(
        normalizedTicket.jiraKey,
        productStage.agentOutput.parsed,
        this.extractGeneratedPrd(productStage.enrichedPrdDocument, productStage.agentOutput)
      );
      if (!completedStages.has("PRD_VALIDATION")) {
        await indexer.indexPrd(
          normalizedTicket.jiraTicketId,
          normalizedTicket.jiraKey,
          productStage.agentOutput.parsed
        );
      }

      let implementationBranch: string | undefined;
      let qaHandoff: QaHandoff | undefined;
      let implementationOutput: AgentOutput<ImplementationOutput>;
      if (!completedStages.has("ENGINEERING_AGENT")) {
        const engStage = await this.runEngineeringAgent(
          pipelineId,
          normalizedTicket,
          productStage.agentOutput.parsed,
          productStage.enrichedPrdDocument
        );
        try {
          const codingResult = await this.runEngineeringCodingAgent(
            pipelineId,
            normalizedTicket,
            productStage.agentOutput.parsed,
            engStage.output,
            productStage.enrichedPrdDocument,
            engStage.stageLogId
          );
          implementationBranch = codingResult.implementationBranch;
          qaHandoff = codingResult.qaHandoff;
          implementationOutput = codingResult.output;
        } catch (err) {
          await pipelineRepo
            .failStage(engStage.stageLogId, err instanceof Error ? err.message : String(err))
            .catch(() => undefined);
          throw err;
        }
      } else {
        const engLog = await pipelineRepo.getStageOutput(pipelineId, "ENGINEERING_AGENT");
        const engOutput = engLog?.output as (ImplementationOutput & {
          implementationBranch?: string;
          qaHandoff?: QaHandoff;
        }) | null;
        const parsed = engOutput as unknown as ImplementationOutput;
        implementationBranch = engOutput?.implementationBranch;
        qaHandoff = engOutput?.qaHandoff;
        implementationOutput = {
          raw: JSON.stringify(engLog?.output),
          parsed,
          metadata: { inputTokens: 0, outputTokens: 0, costUsd: 0, durationMs: 0 },
        };
        // Re-run coding only when nothing was produced AND no branch was
        // pushed — a pushed branch means code already exists on the remote.
        const needsCoding =
          !implementationBranch &&
          !parsed.codingSummary?.trim() &&
          !(parsed.codeChanges?.length);
        if (needsCoding) {
          // Start a fresh stage log so the re-run's output (including the
          // pushed branch) is persisted for subsequent resumes.
          const codingLog = await pipelineRepo.startStage({
            pipelineId,
            stage: "ENGINEERING_AGENT",
            inputJson: {
              resume: true,
              reason: "coding_output_missing",
            } as Prisma.InputJsonValue,
          });
          try {
            const codingResult = await this.runEngineeringCodingAgent(
              pipelineId,
              normalizedTicket,
              productStage.agentOutput.parsed,
              implementationOutput,
              productStage.enrichedPrdDocument,
              codingLog.id
            );
            implementationBranch = codingResult.implementationBranch;
            qaHandoff = codingResult.qaHandoff;
            implementationOutput = codingResult.output;
          } catch (err) {
            await pipelineRepo
              .failStage(codingLog.id, err instanceof Error ? err.message : String(err))
              .catch(() => undefined);
            throw err;
          }
        }
      }

      let implementationValidation: GateResult;
      const implValLog = await pipelineRepo.getStageOutput(pipelineId, "IMPLEMENTATION_VALIDATION");
      if (implValLog?.validationResult) {
        implementationValidation = asGateResult(
          "implementation",
          implValLog.validationResult as unknown as ValidationResult
        );
      } else {
        implementationValidation = await this.validateImplementationStage(
          pipelineId,
          implementationOutput,
          productStage.agentOutput.parsed,
          normalizedTicket,
          productStage.enrichedPrdDocument
        );
      }
      if (
        !(await applyGateDecision(pipelineId, "implementation", implementationValidation))
      ) {
        await ticketRepo.setStatus(ticket.id, "AWAITING_HUMAN");
        return;
      }
      if (!completedStages.has("IMPLEMENTATION_VALIDATION")) {
        await indexer.indexImplementation(
          normalizedTicket.jiraTicketId,
          normalizedTicket.jiraKey,
          implementationOutput.parsed
        );
      }

      let qaStage: {
        agentOutput: AgentOutput<QaOutput>;
        executionReport?: QaExecutionReport;
        toolCallLog: unknown[];
      };
      if (!completedStages.has("QA_AGENT")) {
        qaStage = await this.runQaAgent(
          pipelineId,
          normalizedTicket.jiraKey,
          productStage.agentOutput.parsed,
          implementationOutput.parsed,
          implementationBranch,
          qaHandoff
        );
      } else {
        const qaLog = await pipelineRepo.getStageOutput(pipelineId, "QA_AGENT");
        const out = qaLog?.output as {
          qa: QaOutput;
          executionReport?: QaExecutionReport;
        } | null;
        if (!out?.qa) throw new Error("QA stage output missing on resume");
        qaStage = {
          agentOutput: {
            raw: JSON.stringify(out.qa),
            parsed: out.qa,
            metadata: { inputTokens: 0, outputTokens: 0, costUsd: 0, durationMs: 0 },
          },
          executionReport: out.executionReport,
          toolCallLog: [],
        };
      }
      const qaOutput = qaStage.agentOutput;

      const canaryChangedFilesResume = (implementationOutput.parsed.codeChanges ?? [])
        .map((c) => c.filePath)
        .filter(Boolean);
      const canaryResult = await runCanaryWithTimeout({
        pipelineId,
        jiraKey: normalizedTicket.jiraKey,
        trigger: "pipeline",
        environment: "staging",
        scope: canaryChangedFilesResume.length > 0 ? "changed_files" : "full",
        orientation: {
          prdSummary: productStage.agentOutput.parsed.title,
          implementationSummary: implementationOutput.parsed.summary,
          qaSummary: qaOutput.parsed.testSummary,
          changedFiles: canaryChangedFilesResume,
        },
      });

      let qaValidation: GateResult;
      const qaValLog = await pipelineRepo.getStageOutput(pipelineId, "QA_VALIDATION");
      if (qaValLog?.validationResult) {
        qaValidation = asGateResult(
          "qa",
          qaValLog.validationResult as unknown as ValidationResult
        );
      } else {
        qaValidation = await this.validateQaStage(
          pipelineId,
          qaOutput,
          productStage.agentOutput.parsed,
          qaStage,
          normalizedTicket,
          canaryResult
        );
      }
      if (!(await applyGateDecision(pipelineId, "qa", qaValidation))) {
        await ticketRepo.setStatus(ticket.id, "AWAITING_HUMAN");
        return;
      }
      // Write QA results to Jira only after the QA gate passes — otherwise the
      // ticket would show QA as done while the pipeline is paused for review.
      await writeQaToTicket(
        normalizedTicket.jiraKey,
        qaOutput.parsed,
        qaStage.executionReport
      );

      if (canaryResult?.findings.length) {
        await auditRepo.log(pipelineId, "CANARY_FINDINGS", {
          runId: canaryResult.runId,
          count: canaryResult.findings.length,
          critical: canaryResult.findings.filter((f) => f.severity === "critical").length,
        });
      }

      // Update PR body with QA results + mark ready for review
      await updatePrAfterQa(
        normalizedTicket.jiraKey,
        qaOutput.parsed,
        productStage.agentOutput.parsed,
        implementationOutput.parsed.codingSummary ?? implementationOutput.parsed.summary,
        qaStage.executionReport as Record<string, unknown> | undefined
      );

      await indexer.indexQaReport(
        normalizedTicket.jiraTicketId,
        normalizedTicket.jiraKey,
        qaOutput.parsed
      );

      const generatedPrd = this.extractGeneratedPrd(productStage.enrichedPrdDocument, productStage.agentOutput);
      const canaryCriticals = canaryResult?.findings
        .filter((f) => f.severity === "critical")
        .map((f) => ({ title: f.title, description: f.description })) ?? [];

      const jiraResult = await this.completeOutputStage(pipelineId, normalizedTicket.jiraKey, {
        prd: productStage.agentOutput.parsed,
        generatedPrd,
        implementation: implementationOutput.parsed,
        qa: qaOutput.parsed,
        executionReport: qaStage.executionReport as Record<string, unknown> | undefined,
        validations: {
          prd: prdValidation,
          implementation: implementationValidation,
          qa: qaValidation,
        },
        canaryCriticals,
      });

      await orgIntelligence.capturePipelineComplete({
        pipelineId,
        jiraKey: normalizedTicket.jiraKey,
        components: normalizedTicket.components ?? [],
        prd: productStage.agentOutput.parsed,
        implementation: implementationOutput.parsed,
        qa: qaOutput.parsed,
        validations: { prd: prdValidation, implementation: implementationValidation, qa: qaValidation },
      });

      await auditRepo.log(pipelineId, "JIRA_WRITEBACK_COMPLETED", {
        jiraKey: normalizedTicket.jiraKey,
        ...jiraResult,
      });

      await this.publishCompletedRunSummary({
        pipelineId,
        jiraKey: normalizedTicket.jiraKey,
        prd: productStage.agentOutput.parsed,
        implementation: implementationOutput.parsed,
        qa: qaOutput.parsed,
        implementationBranch,
        executionReport: qaStage.executionReport as Record<string, unknown> | undefined,
      });
      await stateManager.complete(pipelineId);
      await ticketRepo.setStatus(ticket.id, "COMPLETED");
      logger.info({ pipelineId }, "pipeline resume completed");
    } catch (err) {
      if (err instanceof DiscoveryPausedError) {
        await ticketRepo.setStatus(ticket.id, "AWAITING_HUMAN");
        return;
      }
      if (err instanceof PipelineCancelledError) {
        logger.info({ pipelineId }, "pipeline resume stopped by user");
        return;
      }
      const message = err instanceof Error ? err.message : String(err);
      const failedPipeline = await pipelineRepo.findById(pipelineId);
      await stateManager.fail(
        pipelineId,
        failedPipeline?.currentStage ?? pipeline.currentStage,
        message
      );
      await ticketRepo.setStatus(ticket.id, "FAILED");
      throw err;
    }
  }

  private loadProductStageFromLog(stageLog: { output: unknown }): {
    agentOutput: AgentOutput<PrdOutput>;
    enrichedPrdDocument: Record<string, unknown>;
  } {
    const output = stageLog.output as Record<string, unknown>;
    const prd = output.prd as PrdOutput;
    const generatedPrd = (output.generatedPrd ?? (output.discovery as Record<string, unknown>)?.generatedPrd) as
      | GeneratedPRD
      | undefined;
    const enrichedPrdDocument: Record<string, unknown> = {
      prdOutput: prd,
      generatedPrd,
      ...(output.discovery ? { discovery: output.discovery } : {}),
    };
    return {
      agentOutput: {
        raw: JSON.stringify(prd),
        parsed: prd,
        metadata: { inputTokens: 0, outputTokens: 0, costUsd: 0, durationMs: 0 },
      },
      enrichedPrdDocument,
    };
  }

  private extractGeneratedPrd(
    enrichedPrdDocument: Record<string, unknown>,
    agentOutput: AgentOutput<PrdOutput>
  ): GeneratedPRD | undefined {
    const fromDoc = enrichedPrdDocument.generatedPrd as GeneratedPRD | undefined;
    if (fromDoc) return fromDoc;
    try {
      return JSON.parse(agentOutput.raw) as GeneratedPRD;
    } catch {
      return undefined;
    }
  }

  private async publishCompletedRunSummary(input: {
    pipelineId: string;
    jiraKey: string;
    prd: PrdOutput;
    implementation: ImplementationOutput;
    qa: QaOutput;
    implementationBranch?: string;
    executionReport?: Record<string, unknown>;
  }): Promise<void> {
    const summary = buildPipelineRunSummary(input);
    publishPipelineArtifact({
      pipelineId: input.pipelineId,
      jiraKey: input.jiraKey,
      type: "RUN_SUMMARY",
      producer: "pipeline",
      title: `Completed ${input.jiraKey}`,
      payload: summary as unknown as Record<string, unknown>,
    });
    await auditRepo.log(input.pipelineId, "PIPELINE_RUN_SUMMARY", summary);
    logger.info(
      {
        pipelineId: input.pipelineId,
        jiraKey: input.jiraKey,
        branch: summary.branch,
        filesChanged: summary.filesChanged.length,
      },
      "pipeline run summary published — marked completed"
    );
  }

  private async completeOutputStage(
    pipelineId: string,
    jiraKey: string,
    payload: Parameters<typeof completeTicketInJira>[1]
  ) {
    const stageLog = await pipelineRepo.startStage({
      pipelineId,
      stage: "OUTPUT",
      inputJson: { jiraKey, payload } as unknown as Prisma.InputJsonValue,
    });
    const result = await completeTicketInJira(jiraKey, payload);
    await pipelineRepo.completeStage({
      stageLogId: stageLog.id,
      output: result as unknown as Prisma.InputJsonValue,
    });
    return result;
  }

  private async ingest(
    pipelineId: string,
    ticket: NormalizedTicket
  ): Promise<void> {
    const stamped = stampOriginalTicket(ticket);
    Object.assign(ticket, stamped);
    const pipeline = await pipelineRepo.findById(pipelineId);
    if (pipeline?.ticketId) {
      await ticketRepo.patchNormalizedData(pipeline.ticketId, {
        originalTicket: ticket.originalTicket,
      });
    }
    const log = await pipelineRepo.startStage({
      pipelineId,
      stage: "INGESTION",
      inputJson: ticket as unknown as Prisma.InputJsonValue,
    });
    await indexer.indexTicket(ticket);
    await pipelineRepo.completeStage({
      stageLogId: log.id,
      output: { indexed: true, jiraKey: ticket.jiraKey },
    });
    await stateManager.advance(pipelineId, "PRODUCT_AGENT");
  }

  private async runProductAgent(
    pipelineId: string,
    _jiraKey: string,
    ticket: NormalizedTicket
  ): Promise<{
    agentOutput: AgentOutput<PrdOutput>;
    enrichedPrdDocument: Record<string, unknown>;
  }> {
    if (ticket.pmContext) {
      const ctx = ticket.pmContext;
      const stageLog = await pipelineRepo.startStage({
        pipelineId,
        stage: "PRODUCT_AGENT",
        inputJson: {
          mode: "pm_prd",
          jiraKey: ticket.jiraKey,
          source: ctx.source,
        } as unknown as Prisma.InputJsonValue,
      });

      const output: AgentOutput<PrdOutput> = {
        raw: JSON.stringify(ctx.generatedPrd),
        parsed: ctx.prdOutput,
        metadata: {
          inputTokens: 0,
          outputTokens: 0,
          costUsd: 0,
          durationMs: 0,
        },
      };

      await pipelineRepo.completeStage({
        stageLogId: stageLog.id,
        output: {
          prd: ctx.prdOutput,
          generatedPrd: ctx.generatedPrd,
          source: "pm_agents",
          skippedDiscovery: true,
          systemDesign: ctx.enrichedPrdDocument.pmSystemDesign ?? null,
          taskBreakdown: ctx.enrichedPrdDocument.pmTaskBreakdown ?? null,
        } as unknown as Prisma.InputJsonValue,
        confidenceScore: ctx.prdOutput.confidenceScore,
        tokenCount: 0,
        costUsd: 0,
      });
      mirrorPmContextArtifacts({ pipelineId, pmContext: ctx });
      await stateManager.advance(pipelineId, "PRD_VALIDATION");
      return { agentOutput: output, enrichedPrdDocument: ctx.enrichedPrdDocument };
    }

    const stageLog = await pipelineRepo.startStage({
      pipelineId,
      stage: "PRODUCT_AGENT",
      inputJson: {
        mode: "discovery",
        jiraKey: ticket.jiraKey,
      } as unknown as Prisma.InputJsonValue,
    });

    let discovery;
    try {
      const prior = await pipelineRepo.getStageOutput(pipelineId, "PRODUCT_AGENT");
      const priorOut = prior?.output as Record<string, unknown> | undefined;
      let resume: DiscoveryPauseSnapshot | undefined;
      if (priorOut?.paused && priorOut.discovery && typeof priorOut.discovery === "object") {
        const paused = priorOut.discovery as Record<string, unknown>;
        resume = {
          ticketAnalysis: (paused.ticketAnalysis ?? undefined) as DiscoveryPauseSnapshot["ticketAnalysis"],
          historicalIntelligence: (paused.historicalIntelligence ?? undefined) as DiscoveryPauseSnapshot["historicalIntelligence"],
          gapAnalysis: (paused.gapAnalysis ?? undefined) as DiscoveryPauseSnapshot["gapAnalysis"],
          retrievalContext: Array.isArray(paused.retrievalContext)
            ? (paused.retrievalContext as DiscoveryPauseSnapshot["retrievalContext"])
            : [],
          discoveryQuestions: Array.isArray(priorOut.discoveryQuestions)
            ? (priorOut.discoveryQuestions as DiscoveryPauseSnapshot["discoveryQuestions"])
            : undefined,
          pauseReason:
            priorOut.pauseReason === "ambiguities" ||
            priorOut.pauseReason === "blocking_gaps" ||
            priorOut.pauseReason === "needs_clarification"
              ? priorOut.pauseReason
              : "ambiguities",
        };
      }
      discovery = await runDiscovery(ticket, pipelineId, {
        humanAnswers: ticket.humanAnswers,
        resume,
        skipHumanPause:
          Boolean(resume) &&
          answersCoverAllQuestions(resume?.discoveryQuestions, ticket.humanAnswers),
      });
    } catch (err) {
      if (err instanceof DiscoveryPausedError) {
        const snap = err.snapshot;
        await pipelineRepo.completeStage({
          stageLogId: stageLog.id,
          output: {
            paused: true,
            blockingGaps: err.blockingGaps,
            pauseReason: snap?.pauseReason ?? "blocking_gaps",
            discoveryQuestions: snap?.discoveryQuestions ?? [],
            scores: null,
            discovery: snap
              ? {
                  ticketAnalysis: snap.ticketAnalysis ?? null,
                  historicalIntelligence: snap.historicalIntelligence ?? null,
                  gapAnalysis: snap.gapAnalysis ?? null,
                  retrievalContext: snap.retrievalContext ?? [],
                }
              : { retrievalContext: [] },
          } as unknown as Prisma.InputJsonValue,
          status: "AWAITING_HUMAN",
        });
      }
      throw err;
    }

    const output: AgentOutput<PrdOutput> = {
      raw: JSON.stringify(discovery.prd),
      parsed: discovery.prdOutput,
      metadata: {
        inputTokens: discovery.totalTokensUsed,
        outputTokens: 0,
        costUsd: discovery.totalCostUsd,
        durationMs: discovery.durationMs,
      },
    };

    const enrichedPrdDocument: Record<string, unknown> = {
      prdOutput: discovery.prdOutput,
      generatedPrd: discovery.prd,
      historicalIntelligence: discovery.historicalIntelligence,
      ticketAnalysis: discovery.ticketAnalysis,
      gapAnalysis: discovery.gapAnalysis,
      complexityAssessment: discovery.complexityAssessment,
      scores: discovery.scores,
      toolCallLog: discovery.toolCallLog,
      synthesisSummary: {
        historicalCoverage: discovery.historicalIntelligence.historicalCoverage,
        reusedPatterns: discovery.historicalIntelligence.successPatterns,
        knownFailures: discovery.historicalIntelligence.knownFailures,
        impliedRequirements: discovery.historicalIntelligence.impliedRequirements,
        reuseOpportunities: discovery.historicalIntelligence.reuseOpportunities,
        blockingGaps: discovery.gapAnalysis.blockingGaps,
      },
    };

    await pipelineRepo.completeStage({
      stageLogId: stageLog.id,
      output: {
        prd: discovery.prdOutput,
        generatedPrd: discovery.prd,
        scores: discovery.scores,
        toolCallLog: discovery.toolCallLog,
        discovery: {
          ticketAnalysis: discovery.ticketAnalysis,
          historicalIntelligence: discovery.historicalIntelligence,
          gapAnalysis: discovery.gapAnalysis,
          complexityAssessment: discovery.complexityAssessment,
          generatedPrd: discovery.prd,
          retrievalContext: discovery.retrievalContext,
        },
      } as unknown as Prisma.InputJsonValue,
      confidenceScore: discovery.scores.prdQualityScore,
      tokenCount: discovery.totalTokensUsed,
      costUsd: discovery.totalCostUsd,
    });
    await stateManager.advance(pipelineId, "PRD_VALIDATION");
    return { agentOutput: output, enrichedPrdDocument };
  }

  private async validatePrdStage(
    pipelineId: string,
    output: AgentOutput<PrdOutput>,
    ticket: NormalizedTicket,
    enrichedPrdDocument: Record<string, unknown>
  ): Promise<GateResult> {
    const stageLog = await pipelineRepo.startStage({
      pipelineId,
      stage: "PRD_VALIDATION",
      inputJson: output.parsed as unknown as Prisma.InputJsonValue,
    });
    const generatedPrd = this.extractGeneratedPrd(enrichedPrdDocument, output);
    const result = await runGate("prd", {
      prd: output.parsed,
      generatedPrd,
      normalizedTicket: ticket,
      ticket: extractOriginalTicket(ticket),
      prdSource: ticket.pmContext ? "pm_agents" : "discovery",
    });
    await pipelineRepo.completeStage({
      stageLogId: stageLog.id,
      output: result as unknown as Prisma.InputJsonValue,
      validationResult: result as unknown as Prisma.InputJsonValue,
      status: result.passed ? "COMPLETED" : "AWAITING_HUMAN",
    });
    return result;
  }

  private resolveImplementationContext(
    ticket: NormalizedTicket,
    enrichedPrdDocument: Record<string, unknown>
  ) {
    const generatedPrd =
      ticket.pmContext?.generatedPrd ??
      (enrichedPrdDocument.generatedPrd as GeneratedPRD | undefined);
    const modeInput = { generatedPrd, pmContext: ticket.pmContext, ticket };
    const implementationMode = resolveImplementationMode(modeInput);
    const deliverableFiles = resolveDeliverableFiles(modeInput);
    const targetFilePaths = resolveTargetFilePaths(modeInput);
    return { generatedPrd, implementationMode, deliverableFiles, targetFilePaths };
  }

  private async runEngineeringAgent(
    pipelineId: string,
    ticket: NormalizedTicket,
    prd: PrdOutput,
    enrichedPrdDocument: Record<string, unknown>
  ): Promise<{ output: AgentOutput<ImplementationOutput>; stageLogId: string }> {
    const { generatedPrd, implementationMode, deliverableFiles, targetFilePaths } =
      this.resolveImplementationContext(ticket, enrichedPrdDocument);
    const query = `${prd.title} ${prd.problemStatement} ${prd.proposedSolution}`;
    const scope = resolveRepoScope();
    const branch = scope?.defaultBranch ?? "main";

    const unified = await unifiedRetriever.retrieveUnified(query, {
      ticketTypes: ["prd", "implementation", "ticket"],
      codebase: { branchName: branch, topK: 10 },
      topKTotal: 12,
      currentJiraKey: ticket.jiraKey,
    });

    const codebaseIntelligence = await this.getCodebaseIntelligenceSnapshot(prd);
    const prewrite = await gatherTechPrewriteContext({
      pipelineId,
      jiraKey: ticket.jiraKey,
      prd,
      generatedPrd,
      branchName: branch,
      skipCodebase: true,
    });
    const techPrewriteContext = {
      selectedModelLabel: prewrite.selectedModelLabel,
      codebaseIntelligenceBlock: codebaseIntelligence.snapshotText,
      databaseCatalogBlock: prewrite.databaseCatalogBlock,
      databaseConnected: prewrite.databaseConnected,
      mustAskForDatabase: prewrite.mustAskForDatabase,
      logIntelligenceBlock: prewrite.logIntelligenceBlock,
      logsConnected: prewrite.logsConnected,
      entirePrd: generatedPrd ?? prd,
    };
    const enrichedPrdSummary = this.buildEnrichedPrdSummary(enrichedPrdDocument);
    const context = buildEngineeringAgentContext(
      prd,
      unified.retrievedContext.length > 0
        ? unified.retrievedContext
        : await retriever.retrieveForEngineeringAgent(prd, ticket.jiraKey),
      [
        `Selected Tech LLM: ${prewrite.selectedModelLabel}`,
        enrichedPrdSummary,
        "Unified retrieval (tickets + codebase):",
        unified.fusedBlock,
        codebaseIntelligence.snapshotText,
        prewrite.databaseCatalogBlock,
        prewrite.logIntelligenceBlock,
        prewrite.mustAskForDatabase
          ? "DATABASE REQUIRED BUT NOT CONNECTED — do not invent schema; add a blocker asking Settings → Integrations."
          : "",
      ]
        .filter(Boolean)
        .join("\n\n")
    );
    const input = {
      context,
      enrichedPrdDocument,
      codebaseIntelligence,
      techPrewriteContext,
      prd,
      instruction:
        implementationMode === "content"
          ? "Produce a content implementation plan with targetFiles for every deliverable document."
          : "Produce an implementation plan mapped to every acceptance criterion.",
      implementationMode,
      deliverableFiles,
      targetFilePaths,
    };
    const stageLog = await pipelineRepo.startStage({
      pipelineId,
      stage: "ENGINEERING_AGENT",
      inputJson: input as unknown as Prisma.InputJsonValue,
    });
    const output = await this.engineeringAgent.run(
      pipelineId,
      JSON.stringify(input, null, 2),
      {
        systemPrompt: buildEngineeringAgentSystemPrompt(implementationMode),
        jsonMode: true,
        maxTokens: implementationMode === "content" ? 12_000 : 8_000,
      }
    );
    output.parsed = normalizeImplementationOutput(
      output.parsed,
      implementationMode,
      targetFilePaths
    );
    output.parsed.implementationMode =
      output.parsed.implementationMode ?? implementationMode;
    output.parsed.targetFiles =
      output.parsed.targetFiles?.length ? output.parsed.targetFiles : targetFilePaths;
    publishPipelineArtifact({
      pipelineId,
      jiraKey: ticket.jiraKey,
      type: "IMPLEMENTATION_PLAN",
      producer: "engineering",
      title: "Implementation plan",
      payload: output.parsed as unknown as Record<string, unknown>,
    });
    // Stage log completed after coding agent finishes (see runEngineeringCodingAgent).
    return { output, stageLogId: stageLog.id };
  }

  private async runEngineeringCodingAgent(
    pipelineId: string,
    ticket: NormalizedTicket,
    prd: PrdOutput,
    implementationOutput: AgentOutput<ImplementationOutput>,
    enrichedPrdDocument: Record<string, unknown>,
    stageLogId: string | null
  ): Promise<{
    output: AgentOutput<ImplementationOutput>;
    implementationBranch: string;
    qaHandoff: QaHandoff;
  }> {
    await auditRepo.log(pipelineId, "ENGINEERING_CODING_STARTED", {
      jiraKey: ticket.jiraKey,
      hasPmContext: Boolean(ticket.pmContext),
    });
    emitEngineeringCodingEvent({
      type: "coding_started",
      pipelineId,
      jiraKey: ticket.jiraKey,
      timestamp: new Date().toISOString(),
    });

    const sourceBranch = await resolveRepoIndexBranch(
      resolveRepoScope()?.defaultBranch ?? resolveCodingBranchName()
    );
    const { implementationMode, deliverableFiles, targetFilePaths } =
      this.resolveImplementationContext(ticket, enrichedPrdDocument);
    const requiredPaths =
      implementationMode === "content"
        ? resolveContentDeliverablePaths({
            deliverableFiles,
            targetFilePaths,
            implementationTargetFiles: implementationOutput.parsed.targetFiles,
          })
        : implementationOutput.parsed.targetFiles?.length
          ? implementationOutput.parsed.targetFiles
          : targetFilePaths;

    const codingDeliverablePaths =
      implementationMode === "content"
        ? requiredPaths
        : [
            ...new Set([
              ...deliverableFiles.map((f) => f.path),
              ...targetFilePaths,
              ...(implementationOutput.parsed.targetFiles ?? []),
            ]),
          ].filter(Boolean);

    // Load cached repo knowledge for conventions injection (non-blocking)
    let repoKnowledge = null;
    try {
      repoKnowledge = await getKnowledge(sourceBranch);
    } catch {
      // Knowledge cache miss is non-fatal
    }

    const skipDependencyInstall = shouldSkipEngineeringDependencyInstall({
      implementationMode,
    });

    // Create a persistent workspace: clone + per-ticket branch (+ npm install for code mode)
    let workspace;
    try {
      workspace = await createEngWorkspace(pipelineId, ticket.jiraKey, sourceBranch, {
        skipDependencyInstall,
      });
      await auditRepo.log(pipelineId, "ENGINEERING_WORKSPACE_CREATED", {
        jiraKey: ticket.jiraKey,
        branchName: workspace.branchName,
        workspaceDir: workspace.workspaceDir,
        sourceBranch,
        skipDependencyInstall,
        implementationMode,
      });
    } catch (err) {
      const message = sanitizeGitShellError(err);
      await auditRepo.log(pipelineId, "ENGINEERING_WORKSPACE_FAILED", {
        jiraKey: ticket.jiraKey,
        sourceBranch,
        error: message,
      });
      logger.error({ pipelineId, sourceBranch, err: message }, "engineering workspace creation failed");
      throw new Error(
        `Engineering workspace creation failed for ${ticket.jiraKey} ` +
          `(clone branch "${sourceBranch}"): ${message}. ` +
          "Verify Git Integration default branch matches an existing remote branch."
      );
    }

    let codingResult: Awaited<ReturnType<typeof runEngineeringCodingAgentic>> | null = null;
    let implementationBranch: string | null = null;
    let pushResult: { sha: string; pushedBranch: string } | null = null;
    let compileFailed = false;
    let compileSkipped = false;

    try {
      // Run the agentic loop (one attempt — agent handles its own verify/fix loop in Phase 2)
      setCodingDeliverablePaths(pipelineId, codingDeliverablePaths);
      codingResult = await runEngineeringCodingAgentic({
        pipelineId,
        jiraKey: ticket.jiraKey,
        prd,
        implementation: implementationOutput.parsed,
        enrichedPrdDocument,
        pmContext: ticket.pmContext,
        retainArtifacts: true,
        implementationMode,
        deliverableFiles,
        requiredDeliverablePaths: codingDeliverablePaths,
        repoKnowledge,
      });

      // Validate deliverables for content mode
      if (implementationMode === "content") {
        if (workspace) {
          const changedFiles = await workspaceGetChangedFiles(workspace.workspaceDir);
          if (changedFiles.length === 0) {
            throw new Error(
              `Content deliverable required ${requiredPaths.length || "at least one"} file(s); agent made no changes. Resume after updating PRD deliverableFiles or re-run.`
            );
          }
          if (requiredPaths.length > 0) {
            reconcileContentDeliverables(
              workspace.workspaceDir,
              requiredPaths,
              changedFiles
            );
            const refreshedChanged = await workspaceGetChangedFiles(workspace.workspaceDir);
            const changedPaths = new Set(
              refreshedChanged.map((f) => normalizeRepoPath(f.path))
            );
            const writtenPaths = getCodingArtifacts(pipelineId).writtenPaths;
            const missing = findMissingContentDeliverables(
              requiredPaths,
              changedPaths,
              writtenPaths,
              workspace.workspaceDir
            );
            if (missing.length > 0) {
              throw new Error(
                `Content deliverable missing files: ${missing.join(", ")}. ` +
                  `Changed ${refreshedChanged.length} of ${requiredPaths.length} required path(s). ` +
                  `Actual changes: ${[...changedPaths].join(", ") || "(none)"}.`
              );
            }
          }
        } else {
          // Legacy in-memory path
          const staged = getCodingArtifacts(pipelineId).stagedFiles;
          if (staged.length === 0) {
            throw new Error(
              `Content deliverable required ${requiredPaths.length || "at least one"} file(s); Ananta staged 0.`
            );
          }
        }
      } else {
        // Code mode — require at least one file change
        if (workspace) {
          const changedFiles = await workspaceGetChangedFiles(workspace.workspaceDir);
          if (changedFiles.length === 0 && codingResult.codeChanges.length === 0) {
            throw new Error(
              "Code implementation required at least one file change; Ananta made no edits. Check workspace access and targetFiles, then re-run."
            );
          }
        } else {
          const staged = getCodingArtifacts(pipelineId).stagedFiles;
          if (codingResult.codeChanges.length === 0 && staged.length === 0) {
            throw new Error(
              "Code implementation required at least one file change; Ananta staged 0 files in fallback mode."
            );
          }
        }
      }

      // Safety gate compile (monorepo-aware: server/, app/, or repo root)
      if (implementationMode !== "content" && workspace) {
        try {
          const compileResult = await runWorkspaceSafetyCompile(workspace.workspaceDir);
          compileFailed =
            !compileResult.skipped && compileResult.exitCode !== 0;
          compileSkipped = Boolean(compileResult.skipped);
          await auditRepo.log(pipelineId, "ENGINEERING_SAFETY_COMPILE", {
            jiraKey: ticket.jiraKey,
            exitCode: compileResult.exitCode,
            success: compileResult.skipped || compileResult.exitCode === 0,
            skipped: compileResult.skipped,
            command: compileResult.command,
            subdir: compileResult.subdir,
            reason: compileResult.reason,
          });
          if (compileFailed) {
            logger.warn(
              {
                pipelineId,
                command: compileResult.command,
                subdir: compileResult.subdir,
                stderr: compileResult.stderr,
              },
              "safety compile failed — committing with [compile-warnings] prefix"
            );
          }
        } catch (compileErr) {
          logger.warn({ pipelineId, compileErr }, "safety compile skipped");
          compileSkipped = true;
        }
      }

      // ── Commit + push via local git (required — QA reads this branch) ───
      let openedPr: import("../integrations/gitProvider").GitPullRequest | null = null;

      if (workspace) {
        const summary =
          codingResult?.codingSummary ?? "Engineering agent changes";
        const commitMessage = compileFailed
          ? `[compile-warnings] [${ticket.jiraKey}] ${summary}`
          : `[${ticket.jiraKey}] ${summary}`;
        try {
          pushResult = await workspaceCommitAndPush(workspace.workspaceDir, commitMessage);

          if (!pushResult) {
            throw new Error(
              "git commit returned nothing after Ananta made file changes"
            );
          }

          implementationBranch = pushResult.pushedBranch;
          await auditRepo.log(pipelineId, "ENGINEERING_PUSHED_TO_BRANCH", {
            jiraKey: ticket.jiraKey,
            targetBranch: pushResult.pushedBranch,
            commitSha: pushResult.sha,
          });
          logger.info(
            { pipelineId, branch: pushResult.pushedBranch, sha: pushResult.sha },
            "engineering workspace committed and pushed"
          );

          // Phase 3: open a draft PR
          try {
            const prTitle = `[${ticket.jiraKey}] ${prd.title}`;
            const prBody = buildPrBody(ticket.jiraKey, prd, codingResult?.codingSummary ?? "");
            openedPr = await gitClient.createPullRequest(
              pushResult.pushedBranch,
              sourceBranch,
              prTitle,
              prBody,
              true // draft
            );
            await auditRepo.log(pipelineId, "ENGINEERING_PR_OPENED", {
              jiraKey: ticket.jiraKey,
              prUrl: openedPr.url,
              prNumber: openedPr.number,
            });
            logger.info(
              { pipelineId, prUrl: openedPr.url },
              "engineering draft PR opened"
            );
          } catch (prErr) {
            logger.warn({ pipelineId, prErr }, "PR creation failed — continuing pipeline");
          }

          // Persist BranchState + Jira writeback
          const changedFiles = await workspaceGetChangedFiles(workspace.workspaceDir).catch(
            () => []
          );
          await persistBranchState(
            ticket.jiraKey,
            pushResult.pushedBranch,
            pushResult.sha,
            changedFiles.map((f) => f.path),
            openedPr,
            sourceBranch
          );

          await writeGitPushToTicket(ticket.jiraKey, {
            targetBranch: pushResult.pushedBranch,
            commitSha: pushResult.sha,
            sourceBranch,
            prUrl: openedPr?.url,
            prNumber: openedPr?.number,
          });
        } catch (pushErr) {
          const message = pushErr instanceof Error ? pushErr.message : String(pushErr);
          await auditRepo.log(pipelineId, "ENGINEERING_PUSH_FAILED", {
            jiraKey: ticket.jiraKey,
            error: message,
          });
          logger.error({ pipelineId, pushErr }, "engineering workspace push failed");
          throw new Error(`Engineering push failed for ${ticket.jiraKey}: ${message}`);
        }
      } else {
        // Fallback: Git Data API push (legacy in-memory path)
        const finalStaged = getCodingArtifacts(pipelineId).stagedFiles;
        if (finalStaged.length > 0) {
          const targetBranch = resolveFallbackApiPushBranch(ticket.jiraKey);
          try {
            const pushFiles = normalizePushFiles(
              finalStaged.map((f) => ({ filePath: f.filePath, content: f.content }))
            );
            const summary =
              codingResult?.codingSummary ?? "Engineering agent changes";
            const commitMessage = compileFailed
              ? `[compile-warnings] [${ticket.jiraKey}] ${summary}`
              : `[${ticket.jiraKey}] ${summary}`;
            const apiPush = await gitClient.pushFilesToBranch(
              targetBranch,
              sourceBranch,
              pushFiles,
              commitMessage
            );
            implementationBranch = targetBranch;
            pushResult = { sha: apiPush.sha, pushedBranch: targetBranch };
            await auditRepo.log(pipelineId, "ENGINEERING_PUSHED_TO_BRANCH", {
              jiraKey: ticket.jiraKey,
              targetBranch,
              filesCount: finalStaged.length,
              commitSha: apiPush.sha,
            });

            try {
              const prTitle = `[${ticket.jiraKey}] ${prd.title}`;
              const prBody = buildPrBody(
                ticket.jiraKey,
                prd,
                codingResult?.codingSummary ?? ""
              );
              openedPr = await gitClient.createPullRequest(
                targetBranch,
                sourceBranch,
                prTitle,
                prBody,
                true
              );
              await auditRepo.log(pipelineId, "ENGINEERING_PR_OPENED", {
                jiraKey: ticket.jiraKey,
                prUrl: openedPr.url,
                prNumber: openedPr.number,
                path: "fallback_api",
              });
            } catch (prErr) {
              logger.warn(
                { pipelineId, prErr },
                "PR creation failed on fallback API path — continuing"
              );
            }

            await persistBranchState(
              ticket.jiraKey,
              targetBranch,
              apiPush.sha,
              finalStaged.map((f) => f.filePath),
              openedPr,
              sourceBranch
            );

            await writeGitPushToTicket(ticket.jiraKey, {
              targetBranch,
              commitSha: apiPush.sha,
              sourceBranch,
              prUrl: openedPr?.url,
              prNumber: openedPr?.number,
            });
          } catch (err) {
            const message = err instanceof Error ? err.message : String(err);
            await auditRepo.log(pipelineId, "ENGINEERING_PUSH_FAILED", {
              jiraKey: ticket.jiraKey,
              targetBranch,
              error: message,
            });
            logger.error({ pipelineId, err }, "fallback API push failed");
            throw new Error(`Engineering push failed for ${ticket.jiraKey}: ${message}`);
          }
        }
      }

      if (!implementationBranch || !pushResult) {
        throw new Error(
          `Engineering push failed for ${ticket.jiraKey}: no branch was pushed to GitHub`
        );
      }

      snapshotCodingArtifacts(pipelineId);
      clearCodingArtifacts(pipelineId);
    } finally {
      // Always destroy workspace even if an error occurred above
      if (workspace) {
        destroyEngWorkspace(pipelineId);
      }
    }

    if (!codingResult) {
      throw new Error("Engineering coding agent did not produce a result");
    }

    const merged: ImplementationOutput = {
      ...implementationOutput.parsed,
      codeChanges: codingResult.codeChanges,
      codingSummary: codingResult.codingSummary,
      // Surface the safety-compile result so the implementation gate can
      // block QA from running against code that does not build.
      compileFailed,
      compileSkipped,
    };

    const output: AgentOutput<ImplementationOutput> = {
      raw: codingResult.raw,
      parsed: merged,
      metadata: {
        inputTokens:
          implementationOutput.metadata.inputTokens +
          codingResult.metadata.inputTokens,
        outputTokens:
          implementationOutput.metadata.outputTokens +
          codingResult.metadata.outputTokens,
        costUsd:
          implementationOutput.metadata.costUsd + codingResult.metadata.costUsd,
        durationMs:
          implementationOutput.metadata.durationMs +
          codingResult.metadata.durationMs,
      },
    };

    publishPipelineArtifact({
      pipelineId,
      jiraKey: ticket.jiraKey,
      type: "CODE_SUMMARY",
      producer: "engineering",
      title: "Code summary",
      payload: {
        codingSummary: codingResult.codingSummary,
        codeChanges: codingResult.codeChanges,
        toolCallLog: codingResult.toolCallLog,
      },
    });

    if (!implementationBranch || !pushResult) {
      throw new Error(
        `QA handoff failed for ${ticket.jiraKey}: code was not pushed to a GitHub branch`
      );
    }
    const qaHandoff = buildReadyQaHandoff({
      jiraKey: ticket.jiraKey,
      implementationBranch,
      commitSha: pushResult.sha,
      filesChanged: codingResult.codeChanges.length,
      codingSummary: codingResult.codingSummary,
      compileFailed,
    });
    await auditRepo.log(pipelineId, "QA_HANDOFF", {
      ...qaHandoff,
    });
    emitEngineeringCodingEvent({
      type: "ready_for_qa",
      pipelineId,
      jiraKey: ticket.jiraKey,
      timestamp: new Date().toISOString(),
      status: 200,
      implementationBranch: qaHandoff.implementationBranch,
    });

    await auditRepo.log(pipelineId, "ENGINEERING_CODING_COMPLETED", {
      jiraKey: ticket.jiraKey,
      filesChanged: codingResult.codeChanges.length,
      toolCalls: codingResult.toolCallLog.length,
      implementationBranch,
      qaHandoff,
    });
    emitEngineeringCodingEvent({
      type: "coding_completed",
      pipelineId,
      jiraKey: ticket.jiraKey,
      timestamp: new Date().toISOString(),
    });

    await writeEngineeringToTicket(ticket.jiraKey, merged);

    if (stageLogId) {
      await pipelineRepo.completeStage({
        stageLogId,
        output: {
          ...merged,
          implementationBranch,
          qaHandoff,
        } as unknown as Prisma.InputJsonValue,
        confidenceScore: merged.confidenceScore,
        tokenCount:
          implementationOutput.metadata.inputTokens +
          codingResult.metadata.inputTokens +
          implementationOutput.metadata.outputTokens +
          codingResult.metadata.outputTokens,
        costUsd:
          implementationOutput.metadata.costUsd + codingResult.metadata.costUsd,
      });
    }

    await stateManager.advance(pipelineId, "IMPLEMENTATION_VALIDATION");
    return { output, implementationBranch, qaHandoff };
  }

  private buildEnrichedPrdSummary(enrichedPrdDocument: Record<string, unknown>): string {
    const synthesis = (enrichedPrdDocument.synthesisSummary ?? {}) as Record<string, unknown>;
    const historicalCoverage = Number(synthesis.historicalCoverage ?? 0);
    const reusedPatterns = Array.isArray(synthesis.reusedPatterns)
      ? synthesis.reusedPatterns
      : [];
    const knownFailures = Array.isArray(synthesis.knownFailures)
      ? synthesis.knownFailures
      : [];
    const impliedRequirements = Array.isArray(synthesis.impliedRequirements)
      ? synthesis.impliedRequirements
      : [];
    const blockingGaps = Number(synthesis.blockingGaps ?? 0);

    const formatItems = (items: unknown[], limit = 5): string =>
      items
        .slice(0, limit)
        .map((item) =>
          typeof item === "string"
            ? item
            : item && typeof item === "object"
              ? JSON.stringify(item)
              : String(item)
        )
        .map((s) => `  - ${s.slice(0, 240)}`)
        .join("\n");

    const lines = [
      "Enriched PRD Intelligence:",
      `- Historical coverage: ${historicalCoverage}`,
      `- Reuse patterns (${reusedPatterns.length}):`,
      formatItems(reusedPatterns) || "  (none)",
      `- Known failures to avoid (${knownFailures.length}):`,
      formatItems(knownFailures) || "  (none)",
      `- Implied requirements (${impliedRequirements.length}):`,
      formatItems(impliedRequirements) || "  (none)",
      `- Blocking gaps: ${blockingGaps}`,
    ];

    return lines.join("\n");
  }

  private async getCodebaseIntelligenceSnapshot(prd: PrdOutput): Promise<{
    branch: string;
    semanticMatches: unknown[];
    featureFiles: unknown[];
    recentChanges: unknown[];
    snapshotText: string;
  }> {
    const scope = resolveRepoScope();
    const branch = scope?.defaultBranch ?? "main";

    try {
      const query = `${prd.title}\n${prd.problemStatement}\n${prd.acceptanceCriteria.join("\n")}`;
      const bundle = await buildEnrichedCodebaseContext({
        query,
        branchName: branch,
        topN: 10,
        fetchFreshContent: false,
        forEngineering: true,
      });

      const semanticMatches = bundle.files.map((f) => ({
        file_path: f.path,
        similarity: f.score,
        summary: f.summary,
        contentSource: f.contentSource,
      }));

      const featureFiles = bundle.files.map((f) => ({
        filePath: f.path,
        summary: f.summary,
        neighbors: f.neighbors,
      }));

      const recentChanges: unknown[] = [];

      const snapshotText = bundle.formatted || [
        `Branch: ${branch}`,
        "No enriched codebase context available.",
      ].join("\n");

      return {
        branch,
        semanticMatches,
        featureFiles,
        recentChanges,
        snapshotText,
      };
    } catch (err) {
      logger.warn({ err, branch }, "codebase intelligence lookup failed for engineering stage");
      return {
        branch,
        semanticMatches: [],
        featureFiles: [],
        recentChanges: [],
        snapshotText: "Unavailable (lookup failed or index not ready).",
      };
    }
  }

  private async validateImplementationStage(
    pipelineId: string,
    output: AgentOutput<ImplementationOutput>,
    prd: PrdOutput,
    ticket: NormalizedTicket,
    enrichedPrdDocument: Record<string, unknown>
  ): Promise<GateResult> {
    const { implementationMode, targetFilePaths, generatedPrd } =
      this.resolveImplementationContext(ticket, enrichedPrdDocument);
    const stageLog = await pipelineRepo.startStage({
      pipelineId,
      stage: "IMPLEMENTATION_VALIDATION",
      inputJson: output.parsed as unknown as Prisma.InputJsonValue,
    });
    const diffEvidence = await this.collectImplementationDiff(pipelineId, output.parsed);
    const result = await runGate("implementation", {
      prd,
      generatedPrd,
      implementation: output.parsed,
      normalizedTicket: ticket,
      ticket: extractOriginalTicket(ticket),
      implementationMode,
      targetFiles: output.parsed.targetFiles?.length
        ? output.parsed.targetFiles
        : targetFilePaths,
      workspaceDiff: diffEvidence.diffText,
      changedFiles: diffEvidence.changedFiles,
      pmRecord: ticket.pmContext
        ? ({
            generatedPrd: ticket.pmContext.generatedPrd,
            codebaseAnalysis: ticket.pmContext.enrichedPrdDocument.pmCodebaseAnalysis,
            ticketInput: {
              summary: ticket.summary,
              description: ticket.description,
              commentsText: ticket.originalTicket?.comments ?? "",
            },
          } as never)
        : undefined,
    });
    await pipelineRepo.completeStage({
      stageLogId: stageLog.id,
      output: result as unknown as Prisma.InputJsonValue,
      validationResult: result as unknown as Prisma.InputJsonValue,
      status: result.passed ? "COMPLETED" : "AWAITING_HUMAN",
    });
    return result;
  }

  private async collectImplementationDiff(
    pipelineId: string,
    implementation: ImplementationOutput
  ): Promise<{
    diffText: string;
    changedFiles: Array<{ path: string; status?: string }>;
  }> {
    const fromOutput = (implementation.codeChanges ?? []).map((c) => ({
      path: c.filePath,
      status: c.action,
    }));
    const workspace = getEngWorkspace(pipelineId);
    if (!workspace) {
      return { diffText: "", changedFiles: fromOutput };
    }
    try {
      let diffText = await workspaceGitDiff(workspace.workspaceDir);
      if (!diffText.trim()) {
        diffText = await workspaceCommittedDiff(workspace.workspaceDir);
      }
      const files = await workspaceGetChangedFiles(workspace.workspaceDir);
      return {
        diffText,
        changedFiles: files.length
          ? files.map((f) => ({ path: f.path, status: f.status }))
          : fromOutput,
      };
    } catch (err) {
      logger.warn({ err, pipelineId }, "implementation diff collection failed");
      return { diffText: "", changedFiles: fromOutput };
    }
  }

  private async runQaAgent(
    pipelineId: string,
    jiraKey: string,
    prd: PrdOutput,
    implementation: ImplementationOutput,
    implementationBranch?: string,
    qaHandoff?: QaHandoff | null
  ) {
    const handoff = await this.resolveQaHandoff(
      pipelineId,
      jiraKey,
      implementation,
      implementationBranch,
      qaHandoff
    );
    const branchName = handoff.implementationBranch;

    logger.info(
      {
        pipelineId,
        jiraKey,
        implementationBranch: branchName,
        qaHandoffStatus: handoff.status,
      },
      "QA agent received Ananta status 200 — generating test cases"
    );

    const retrieved = await retriever.retrieveForQAAgent(prd, jiraKey);
    const input = {
      prd,
      implementation,
      retrievedContext: retrieved,
      implementationBranch: branchName,
      qaHandoff: handoff,
      instruction:
        "Ananta passed status 200. Four-phase QA: understand code, write tests, run tests, report findings.",
    };
    const stageLog = await pipelineRepo.startStage({
      pipelineId,
      stage: "QA_AGENT",
      inputJson: input as unknown as Prisma.InputJsonValue,
    });
    const result = await runQaAgentic({
      pipelineId,
      jiraKey,
      prd,
      implementation,
      retrievedContext: retrieved,
      implementationMode: implementation.implementationMode,
      implementationBranch: branchName,
      qaHandoff: handoff,
    });
    const output = result.agentOutput;
    await pipelineRepo.completeStage({
      stageLogId: stageLog.id,
      output: {
        qa: output.parsed,
        executionReport: result.executionReport,
        toolCallLog: result.toolCallLog,
      } as unknown as Prisma.InputJsonValue,
      confidenceScore: output.parsed.confidenceScore,
      tokenCount: output.metadata.inputTokens + output.metadata.outputTokens,
      costUsd: output.metadata.costUsd,
    });
    publishPipelineArtifact({
      pipelineId,
      jiraKey,
      type: "TEST_PLAN",
      producer: "qa",
      title: "QA test plan & report",
      payload: {
        testSummary: output.parsed.testSummary,
        executionReport: result.executionReport ?? null,
        toolCallLog: result.toolCallLog,
      },
    });
    await stateManager.advance(pipelineId, "QA_VALIDATION");
    return result;
  }

  private async resolveQaHandoff(
    pipelineId: string,
    jiraKey: string,
    implementation: ImplementationOutput,
    implementationBranch?: string,
    existing?: QaHandoff | null
  ): Promise<QaHandoff> {
    if (existing?.status === 200) {
      return assertQaHandoffReady(existing);
    }
    const logs = await auditRepo.listForPipeline(pipelineId, 120);
    const ready = logs.find((log) => log.event === "QA_HANDOFF");
    const fromLog = ready?.metadata as QaHandoff | undefined;
    if (fromLog?.status === 200) {
      return assertQaHandoffReady(fromLog);
    }
    const pushLog = logs.find((log) => log.event === "ENGINEERING_PUSHED_TO_BRANCH");
    const meta = pushLog?.metadata as { targetBranch?: string; commitSha?: string } | null;
    const branch =
      implementationBranch?.trim() ||
      meta?.targetBranch?.trim() ||
      (await resolveImplementationBranchForQa(pipelineId, jiraKey));
    const sha = meta?.commitSha?.trim();
    if (!sha) {
      throw new Error(
        `QA agent cannot start for ${jiraKey}: Ananta has not passed status 200 (no GitHub push yet).`
      );
    }
    return buildReadyQaHandoff({
      jiraKey,
      implementationBranch: branch,
      commitSha: sha,
      filesChanged: implementation.codeChanges?.length ?? 0,
      codingSummary: implementation.codingSummary || implementation.summary,
      compileFailed: Boolean(implementation.compileFailed),
    });
  }

  private async validateQaStage(
    pipelineId: string,
    output: AgentOutput<QaOutput>,
    prd: PrdOutput,
    qaStage: { executionReport?: QaExecutionReport },
    ticket: NormalizedTicket,
    canaryResult: Awaited<ReturnType<typeof runCanaryCycle>>
  ): Promise<GateResult> {
    const stageLog = await pipelineRepo.startStage({
      pipelineId,
      stage: "QA_VALIDATION",
      inputJson: output.parsed as unknown as Prisma.InputJsonValue,
    });
    const canaryCriticals =
      canaryResult?.findings
        .filter((f) => f.severity === "critical")
        .map((f) => ({ title: f.title, description: f.description })) ?? [];
    const result = await runGate("qa", {
      prd,
      qa: output.parsed,
      qaExecutionReport: qaStage.executionReport,
      normalizedTicket: ticket,
      ticket: extractOriginalTicket(ticket),
      canaryCriticals,
      canarySkipped: !canaryResult,
      canarySkipReason: !canaryResult
        ? "Canary cycle did not run (disabled or missing staging URL)."
        : undefined,
      ticketText: [ticket.summary, ticket.description, prd.title].join(" "),
    });
    await pipelineRepo.completeStage({
      stageLogId: stageLog.id,
      output: result as unknown as Prisma.InputJsonValue,
      validationResult: result as unknown as Prisma.InputJsonValue,
      status: result.passed ? "COMPLETED" : "AWAITING_HUMAN",
    });
    return result;
  }

  /** Call between expensive stages so Stop session takes effect promptly. */
  private assertNotStopped(pipelineId: string, jiraKey?: string): void {
    assertPipelineNotCancelled(pipelineId, jiraKey);
  }
}

export const orchestrator = new PipelineOrchestrator();
